[package]
name = "sync-vid-network"
version = "0.1.0"
authors = ["bhanuka.ishan@gmail.com"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
matchbox_socket = "0.5.0"
rand = "0.8.5"
futures = "0.3.26"
